### ISSUE TITLE
--template argument should be replaced with a more modular design

### ISSUE THREAD

**Issue by Mafrans** [abschill/create-lit-project#3]
Using a single template argument for all the configurations lit projects can have won't scale well. I would much rather prefer something like 
`npx create-lit-project --lang=typescript --style=sass`  
or simply 
`npx create-lit-project --typescript --sass`

This might require some tweaks in how templates are loaded, but should make for a much more comfortable and scalable solution.

**Comment by abschill** [comment]
yea was thinking to go to something like that in order to allow a type (lang) and subtype (minimalism -> opinionated) w/styles/server moving forward, ill push up a new patch this weekend with something along these lines

**Comment by abschill** [comment]
https://github.com/abschill/create-lit-project/blob/0.1.6/temp/example-0.1.6.png

Branched a new concept for the argument parsing setup let me know if this is was what you were thinking along the lines of, or if its missing any of the idea you were visualizing this is how I was thinking of having it work with base lang + style setup as the 2 "parameters" and then stuff like setting up a little server / using decorators and such being "options", then the base path argument being its own thing resolving . to the process.cwd(), and if the first argument contains - (meaning its a param or an option) then it defaults to '' to basically just use cwd

**Comment by abschill** [comment]
done
